server:
   port: 9000
spring:
   datasource:
      generate-unique-name: false
      name: auth-server
      username: alberto
      password: 12345
   jpa:
      show-sql: true
   h2:
      console:
         enabled: true